"""empty message

Revision ID: f35d946ac3c6
Revises: 878dc4908871
Create Date: 2022-05-16 02:35:36.254169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35d946ac3c6'
down_revision = '878dc4908871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blogTitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blogTitle')
    # ### end Alembic commands ###
